language: php
php:
  - '5.6'
  - '7.0'
  - hhvm
  - nightly
install: composer install -o --no-interaction
script: vendor/bin/phpunit --bootstrap vendor/autoload.php --coverage-clover=coverage.xml
after_success:
    - bash <(curl -s https://codecov.io/bash)
